check logs 7

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -66,7 +66,7 @@ jobs:
           cd tests
           pytest -v assn3_tests.py > assn3_test_results.txt
       - name: Log Test Status
-        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> ../log.txt; else echo "tests failed" >> ../log.txt; fi
+        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> $GITHUB_WORKSPACE/log.txt; else echo "tests failed" >> $GITHUB_WORKSPACE/log.txt; fi
       - name: upload test results
         if: always()
         uses: actions/upload-artifact@v3
@@ -78,7 +78,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: GH_assn3_log
-          path: ../log.txt
+          path: $GITHUB_WORKSPACE/log.txt
 
       # - name: Set DATE
       #   run: echo "DATE=$(date -I)" >> $GITHUB_ENV
