check logs

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -12,6 +12,10 @@ jobs:
         uses: actions/checkout@v3
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
+      - name: Log Start Time
+        run: echo "$(date --Iminutes)"> log.txt
+      - name: Log Submitter Name
+        run: echo "Michal Ad and Roni Rosen" >> log.txt
       - name: Build Docker image and export
         uses: docker/build-push-action@v3
         with:
@@ -19,8 +23,8 @@ jobs:
           file: ./Dockerfile
           tags: meals_service:latest
           outputs: type=docker,dest=/tmp/image.tar
-        #   echo "image successfully built" >> log.txt || echo "image not able to be built" >> log.txt
-
+      - name: Log Image Built Status
+        run: if [ $? -eq 0 ]; then echo "image successfully built" >> log.txt; else echo "image not able to be built" >> log.txt; fi
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
@@ -41,6 +45,8 @@ jobs:
         run: docker image ls
       - name: run image in container
         run: docker run -d -p8000:8000 meals_service
+      - name: Log Container Status
+        run: if [ $? -eq 0 ]; then echo "Container up and running" >> log.txt; else echo "Container failed to run" >> log.txt; fi
       - name: Check container is running
         run: docker ps
       # set up python and pytest environment
@@ -59,41 +65,20 @@ jobs:
         run: |
           cd tests
           pytest -v assn3_tests.py > assn3_test_results.txt
+      - name: Log Test Status
+        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> log.txt; else echo "tests failed" >> log.txt; fi
       - name: upload test results
         if: always()
         uses: actions/upload-artifact@v3
         with:
           name: GH_assn3_test_results
           path: tests/assn3_test_results.txt
+      - name: upload log file
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: GH_assn3_log
+          path: log.txt
 
       # - name: Set DATE
       #   run: echo "DATE=$(date -I)" >> $GITHUB_ENV
-
-      # push to github?? why dockerhub
-
-
-#  query:
-#    needs: test
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v2
-#
-#      - name: Run Docker container
-#        id: run
-#        run: |
-#          docker run -d -p 8000:8000 myservice
-#
-#      - name: Issue queries to the service
-#        run: |
-#          # insert your code here to issue queries and save results in a file
-#
-#      - name: Upload artifacts
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: output
-#          path: |
-#            log.txt
-#            assn3_test_results.txt
-#            # path to your query results file
