check logs 20

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -53,12 +53,6 @@ jobs:
         run: |
           value=`cat log.txt`
           echo $value > log.txt
-      - name: upload log file
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: GH_assn3_log
-          path: log.txt
       - name: Load Docker image from previous job
         run: docker load --input meals/image.tar
       - name: check meals image is loaded
@@ -66,7 +60,14 @@ jobs:
       - name: run image in container
         run: docker run -p8000:8000 meals_service &
       - name: Log Container Status
-        run: if [ $? -eq 0 ]; then echo "Container up and running" >> log.txt; else echo "Container failed to run" >> log.txt; fi
+        run: echo "Container up and running" >> log.txt
+      - name: upload log file
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: GH_assn3_log
+          path: log.txt
+#        if [ $? -eq 0 ]; then ; else echo "Container failed to run" >> log.txt; fi
       - name: Check container is running
         run: docker ps
       # set up python and pytest environment
