check logs 12

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -34,7 +34,7 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v3
         with:
-          name: GH_assn3_log
+          name: build-log
           path: log.txt
       
   test:
@@ -52,7 +52,7 @@ jobs:
       - name: run image in container
         run: docker run -p8000:8000 meals_service &
       - name: Log Container Status
-        run: if [ $? -eq 0 ]; then echo "Container up and running" >> log.txt; else echo "Container failed to run" >> log.txt; fi
+        run: if [ $? -eq 0 ]; then echo "Container up and running" >> log2.txt; else echo "Container failed to run" >> log2.txt; fi
       - name: Check container is running
         run: docker ps
       # set up python and pytest environment
@@ -72,7 +72,7 @@ jobs:
           cd tests
           pytest -v assn3_tests.py > assn3_test_results.txt
       - name: Log Test Status
-        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> log.txt; else echo "tests failed" >> log.txt; fi
+        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> log2.txt; else echo "tests failed" >> log2.txt; fi
       - name: upload test results
         if: always()
         uses: actions/upload-artifact@v3
@@ -84,7 +84,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: GH_assn3_log
-          path: log.txt
+          path: log2.txt
 
       # - name: Set DATE
       #   run: echo "DATE=$(date -I)" >> $GITHUB_ENV
