check logs 4

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -13,9 +13,9 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: Log Start Time
-        run: echo "$(date --Iminutes)"> ${{ github.workspace }}/log.txt
+        run: echo "$(date --Iminutes)"> log.txt
       - name: Log Submitter Name
-        run: echo "Michal Ad and Roni Rosen" >> ${{ github.workspace }}/log.txt
+        run: echo "Michal Ad and Roni Rosen" >> log.txt
       - name: Build Docker image and export
         uses: docker/build-push-action@v3
         with:
@@ -24,7 +24,7 @@ jobs:
           tags: meals_service:latest
           outputs: type=docker,dest=/tmp/image.tar
       - name: Log Image Built Status
-        run: if [ $? -eq 0 ]; then echo "image successfully built" >> log.txt; else echo "image not able to be built" >> ${{ github.workspace }}/log.txt; fi
+        run: if [ $? -eq 0 ]; then echo "image successfully built" >> log.txt; else echo "image not able to be built" >> log.txt; fi
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
@@ -44,9 +44,9 @@ jobs:
       - name: check meals image is loaded
         run: docker image ls
       - name: run image in container
-        run: docker run -d -p8000:8000 meals_service
+        run: docker run -p8000:8000 meals_service &
       - name: Log Container Status
-        run: if [ $? -eq 0 ]; then echo "Container up and running" >> log.txt; else echo "Container failed to run" >> ${{ github.workspace }}/log.txt; fi
+        run: if [ $? -eq 0 ]; then echo "Container up and running" > log.txt; else echo "Container failed to run" >> log.txt; fi
       - name: Check container is running
         run: docker ps
       # set up python and pytest environment
@@ -66,7 +66,7 @@ jobs:
           cd tests
           pytest -v assn3_tests.py > assn3_test_results.txt
       - name: Log Test Status
-        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> log.txt; else echo "tests failed" >> ${{ github.workspace }}/log.txt; fi
+        run: if [ $? -eq 0 ]; then echo "tests succeeded" >> log.txt; else echo "tests failed" >> log.txt; fi
       - name: upload test results
         if: always()
         uses: actions/upload-artifact@v3
@@ -78,7 +78,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: GH_assn3_log
-          path: ${{ github.workspace }}/log.txt
+          path: log.txt
 
       # - name: Set DATE
       #   run: echo "DATE=$(date -I)" >> $GITHUB_ENV
