check logs 21

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -60,14 +60,13 @@ jobs:
       - name: run image in container
         run: docker run -p8000:8000 meals_service &
       - name: Log Container Status
-        run: echo "Container up and running" >> log.txt
+        run: if [ $? -eq 0 ]; then echo "Container up and running" >> log.txt; else echo "Container failed to run" >> log.txt; fi
       - name: upload log file
         if: always()
         uses: actions/upload-artifact@v3
         with:
           name: GH_assn3_log
           path: log.txt
-#        if [ $? -eq 0 ]; then ; else echo "Container failed to run" >> log.txt; fi
       - name: Check container is running
         run: docker ps
       # set up python and pytest environment
